// 1. Core Union Types
export type CurrencyCode = 'CHF' | 'USD' | 'EUR' | 'KRW';
export type TargetCurrency = CurrencyCode;
export type ExpenseNature = 'ONE_OFF' | 'RECURRING_MONTHLY' | 'RECURRING_YEARLY';

// 2. Domain Entity: Transaction
export interface Transaction {
  id: string;                         // UUIDv7
  description: string;                // Expense item title (non-empty, max 100)
  transactionTime: string;            // ISO-8601 UTC string (e.g. "2026-09-07T18:30:00.000Z")
  originalAmount: number;             // Original amount (positive float)
  originalCurrency: CurrencyCode;     // Currency code
  category: string;                   // Category (Food, Transport, Housing, etc.)
  expenseNature: ExpenseNature;       // Expense nature / frequency
  isFixed?: boolean;                  // True if this is a recurring fixed expense that applies to current & subsequent months
  isCash?: boolean;                   // True if paid in cash
  isAutoGenerated?: boolean;          // True if dynamically projected from an earlier fixed expense
  parentFixedId?: string;             // Original transaction ID for projected recurring fixed expenses
  stoppedAfterMonth?: string;         // YYYY-MM from which this fixed expense stops recurring (deleted for this month and beyond)
  createdAt: string;                  // ISO-8601 creation time
  updatedAt: string;                  // ISO-8601 updated time
}

// 3. Domain Entity: Daily Exchange Rate Record
export interface ExchangeRateRecord {
  date: string;                       // YYYY-MM-DD
  baseCurrency: 'KRW';                // Fixed base currency
  rates: Record<CurrencyCode, number>; // Value of 1 foreign unit in KRW (e.g. { CHF: 1550.2, USD: 1380.0, EUR: 1495.0, KRW: 1.0 })
  updatedAt: string;
}

// 4. Dynamically Valuated Transaction (View Model)
export interface ValuatedTransaction extends Transaction {
  convertedAmount: number;            // Converted amount in targetCurrency
  targetCurrency: TargetCurrency;     // Current target currency
  appliedRateDate: string;            // Rate record date applied (for LOCF tracking)
}

// 5. Aggregate View Data Structures
export interface DailyAggregate {
  date: string;                       // YYYY-MM-DD
  totalAmount: number;                // Total amount for date in targetCurrency
  itemCount: number;                  // Number of transactions
  transactions: ValuatedTransaction[];// Detailed transactions for that date
}

export interface AnalyticsBreakdown {
  targetCurrency: TargetCurrency;
  grandTotal: number;
  fixedTotal: number;                 // Sum of fixed expenses
  flexibleTotal: number;              // Sum of flexible expenses
  byCategory: Array<{
    category: string;
    totalAmount: number;
    percentage: number;               // 0.00 ~ 100.00
  }>;
  byNature: Array<{
    nature: ExpenseNature;
    totalAmount: number;
    percentage: number;               // 0.00 ~ 100.00
  }>;
}

// 6. Monthly Budget Domain Entity
export interface MonthlyBudget {
  yearMonth: string;                  // YYYY-MM (e.g. "2026-09")
  baseBudget: number;                 // Monthly base budget
  extraBudget: number;                // Extra budget (+/- adjustments)
  totalBudget: number;                // Total Monthly Budget = baseBudget + extraBudget
  fixedBudget?: number;               // Auto-calculated from sum of active fixed expenses
  flexibleBudget?: number;            // Auto-calculated = totalBudget - fixedBudget
  currency: CurrencyCode;             // Currency the budget was set in
  updatedAt: string;
}

export interface CumulativeBudgetInfo {
  startYearMonth: string;             // Starting aggregation month (e.g. "2026-01")
  currentYearMonth: string;           // Ending month (e.g. "2026-09")
  monthsCount: number;                // Number of months aggregated
  totalCumulativeBudget: number;      // Sum of budgets across the months in targetCurrency
  totalActualSpent: number;           // Actual expenditure over the range in targetCurrency
  remainingOrOverAmount: number;      // totalCumulativeBudget - totalActualSpent
  isOverBudget: boolean;              // true if totalActualSpent > totalCumulativeBudget
  percentageUsed: number;             // Math.round((totalActualSpent / totalCumulativeBudget) * 100)
}

// 7. Repository Contracts
export interface ITransactionRepository {
  create(transaction: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transaction>;
  createBatch(transactions: Array<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>): Promise<Transaction[]>;
  update(id: string, updates: Partial<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>): Promise<Transaction>;
  delete(id: string): Promise<void>;
  getByDateRange(startDate: string, endDate: string): Promise<Transaction[]>;
  getAll(): Promise<Transaction[]>;
}

export interface IExchangeRateRepository {
  getRates(date: string): Promise<ExchangeRateRecord | null>;
  getRatesBatch(dates: string[]): Promise<Record<string, ExchangeRateRecord>>;
  saveRates(record: ExchangeRateRecord): Promise<void>;
  getLatestAvailableRate(targetDate: string): Promise<ExchangeRateRecord | null>;
}

export interface IBudgetRepository {
  getBudget(yearMonth: string): Promise<MonthlyBudget | null>;
  getAllBudgets(): Promise<Record<string, MonthlyBudget>>;
  saveBudget(budget: MonthlyBudget): Promise<void>;
}

// 8. Supabase Database Snake-Case Row Schemas
export interface DbTransaction {
  id: string;
  user_id: string;
  description: string;
  transaction_time: string;
  original_amount: number;
  original_currency: CurrencyCode;
  category: string;
  expense_nature: ExpenseNature;
  is_fixed: boolean;
  is_cash?: boolean;
  is_auto_generated: boolean;
  parent_fixed_id: string | null;
  stopped_after_month: string | null;
  created_at: string;
  updated_at: string;
}

export interface DbMonthlyBudget {
  id?: string;
  user_id: string;
  year_month: string;
  base_budget: number;
  extra_budget: number;
  currency: CurrencyCode;
  updated_at: string;
}

export interface DbUserCategory {
  id?: string;
  user_id: string;
  category_id: string;
  name: string;
  color: string;
  bg_color: string;
  sort_order: number;
  updated_at: string;
}

export interface DbExchangeRate {
  rate_date: string;
  base_currency: 'KRW';
  rates: Record<CurrencyCode, number>;
  updated_at: string;
}
