import type {
  Transaction,
  ITransactionRepository,
  DbTransaction,
} from '../types';
import { supabase, isSupabaseConfigured, ensureAuthUser } from '../services/supabase';
import { LocalStorageTransactionRepository } from './LocalStorageTransactionRepository';

/**
 * Mapper: Convert Database snake_case row to Frontend Domain Transaction
 */
export function toDomainTransaction(row: DbTransaction): Transaction {
  return {
    id: row.id,
    description: row.description,
    transactionTime: row.transaction_time,
    originalAmount: Number(row.original_amount),
    originalCurrency: row.original_currency,
    category: row.category,
    expenseNature: row.expense_nature,
    isFixed: Boolean(row.is_fixed),
    isCash: Boolean(row.is_cash),
    isAutoGenerated: Boolean(row.is_auto_generated),
    parentFixedId: row.parent_fixed_id || undefined,
    stoppedAfterMonth: row.stopped_after_month || undefined,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/**
 * Mapper: Convert Domain Transaction input to Database snake_case insert payload
 */
export function toDbTransactionInsert(
  item: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>,
  userId: string
): Omit<DbTransaction, 'id' | 'created_at' | 'updated_at'> {
  return {
    user_id: userId,
    description: item.description,
    transaction_time: item.transactionTime,
    original_amount: item.originalAmount,
    original_currency: item.originalCurrency,
    category: item.category,
    expense_nature: item.expenseNature,
    is_fixed: Boolean(item.isFixed),
    is_cash: Boolean(item.isCash),
    is_auto_generated: Boolean(item.isAutoGenerated),
    parent_fixed_id: item.parentFixedId || null,
    stopped_after_month: item.stoppedAfterMonth || null,
  };
}

export class SupabaseTransactionRepository implements ITransactionRepository {
  private fallbackRepo = new LocalStorageTransactionRepository();

  async getAll(): Promise<Transaction[]> {
    if (!isSupabaseConfigured || !supabase) {
      return this.fallbackRepo.getAll();
    }

    try {
      const userId = await ensureAuthUser();
      const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .eq('user_id', userId)
        .order('transaction_time', { ascending: false });

      if (error) throw error;
      if (!data || data.length === 0) {
        return [];
      }

      return (data as DbTransaction[]).map(toDomainTransaction);
    } catch (err) {
      console.warn('Supabase fetch failed, falling back to LocalStorage:', err);
      return this.fallbackRepo.getAll();
    }
  }

  async getByDateRange(startDate: string, endDate: string): Promise<Transaction[]> {
    if (!isSupabaseConfigured || !supabase) {
      return this.fallbackRepo.getByDateRange(startDate, endDate);
    }

    try {
      const userId = await ensureAuthUser();
      const startIso = `${startDate}T00:00:00.000Z`;
      const endIso = `${endDate}T23:59:59.999Z`;

      const { data, error } = await supabase
        .from('transactions')
        .select('*')
        .eq('user_id', userId)
        .gte('transaction_time', startIso)
        .lte('transaction_time', endIso)
        .order('transaction_time', { ascending: false });

      if (error) throw error;
      return ((data as DbTransaction[]) || []).map(toDomainTransaction);
    } catch (err) {
      console.warn('Supabase getByDateRange failed, falling back to LocalStorage:', err);
      return this.fallbackRepo.getByDateRange(startDate, endDate);
    }
  }

  async create(item: Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>): Promise<Transaction> {
    // Keep local cache up to date
    const localCreated = await this.fallbackRepo.create(item);

    if (!isSupabaseConfigured || !supabase) {
      return localCreated;
    }

    try {
      const userId = await ensureAuthUser();
      const insertPayload = toDbTransactionInsert(item, userId);

      const { data, error } = await supabase
        .from('transactions')
        .insert(insertPayload)
        .select()
        .single();

      if (error) throw error;
      return toDomainTransaction(data as DbTransaction);
    } catch (err) {
      console.warn('Supabase create failed, stored in LocalStorage:', err);
      return localCreated;
    }
  }

  async createBatch(items: Array<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>): Promise<Transaction[]> {
    const localBatch = await this.fallbackRepo.createBatch(items);

    if (!isSupabaseConfigured || !supabase || items.length === 0) {
      return localBatch;
    }

    try {
      const userId = await ensureAuthUser();
      const insertPayloads = items.map((item) => toDbTransactionInsert(item, userId));

      const { data, error } = await supabase
        .from('transactions')
        .insert(insertPayloads)
        .select();

      if (error) throw error;
      return ((data as DbTransaction[]) || []).map(toDomainTransaction);
    } catch (err) {
      console.warn('Supabase createBatch failed, stored in LocalStorage:', err);
      return localBatch;
    }
  }

  async update(id: string, updates: Partial<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>): Promise<Transaction> {
    if (!isSupabaseConfigured || !supabase) {
      return this.fallbackRepo.update(id, updates);
    }

    try {
      const userId = await ensureAuthUser();
      const dbUpdates: Partial<DbTransaction> = {
        updated_at: new Date().toISOString(),
      };

      if (updates.description !== undefined) dbUpdates.description = updates.description;
      if (updates.transactionTime !== undefined) dbUpdates.transaction_time = updates.transactionTime;
      if (updates.originalAmount !== undefined) dbUpdates.original_amount = updates.originalAmount;
      if (updates.originalCurrency !== undefined) dbUpdates.original_currency = updates.originalCurrency;
      if (updates.category !== undefined) dbUpdates.category = updates.category;
      if (updates.expenseNature !== undefined) dbUpdates.expense_nature = updates.expenseNature;
      if (updates.isFixed !== undefined) dbUpdates.is_fixed = updates.isFixed;
      if (updates.isCash !== undefined) dbUpdates.is_cash = updates.isCash;
      if (updates.isAutoGenerated !== undefined) dbUpdates.is_auto_generated = updates.isAutoGenerated;
      if (updates.parentFixedId !== undefined) dbUpdates.parent_fixed_id = updates.parentFixedId || null;
      if (updates.stoppedAfterMonth !== undefined) dbUpdates.stopped_after_month = updates.stoppedAfterMonth || null;

      const { data, error } = await supabase
        .from('transactions')
        .update(dbUpdates)
        .eq('id', id)
        .eq('user_id', userId)
        .select()
        .single();

      if (error) throw error;

      // Also safely keep local fallback storage in sync if it exists locally
      try {
        await this.fallbackRepo.update(id, updates);
      } catch {
        // Not present in local storage, which is normal when loaded from Supabase
      }

      return toDomainTransaction(data as DbTransaction);
    } catch (err) {
      console.warn('Supabase update failed, attempting LocalStorage fallback:', err);
      return this.fallbackRepo.update(id, updates);
    }
  }

  async delete(id: string): Promise<void> {
    await this.fallbackRepo.delete(id);

    if (!isSupabaseConfigured || !supabase) {
      return;
    }

    try {
      const userId = await ensureAuthUser();
      const { error } = await supabase
        .from('transactions')
        .delete()
        .eq('id', id)
        .eq('user_id', userId);

      if (error) throw error;
    } catch (err) {
      console.warn('Supabase delete failed, deleted in LocalStorage:', err);
    }
  }
}
