import type { ExpenseNature, Transaction } from '../types';

// `isFixed` and the cycle are independent flags; only Fixed + Monthly auto-repeats into later months.
export const isRecurringFixed = (tx: Pick<Transaction, 'isFixed' | 'expenseNature'>): boolean =>
  !!tx.isFixed && tx.expenseNature === 'RECURRING_MONTHLY';

const CYCLE_LABELS: Record<ExpenseNature, string> = {
  ONE_OFF: 'One-off',
  RECURRING_MONTHLY: 'Monthly',
  RECURRING_YEARLY: 'Long-term',
};

export const cycleLabel = (tx: Pick<Transaction, 'isFixed' | 'expenseNature'>): string =>
  `${tx.isFixed ? 'Fixed ' : ''}${CYCLE_LABELS[tx.expenseNature]}`;

// Not yet executed: scheduled after the current moment.
export const isPending = (tx: Pick<Transaction, 'transactionTime'>, now = Date.now()): boolean =>
  new Date(tx.transactionTime).getTime() > now;

const ymOfDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
export const toYearMonth = (iso: string) => ymOfDate(new Date(iso));

const rootOf = (tx: Transaction) => tx.parentFixedId || tx.id;
const titleKey = (tx: Transaction) => tx.description.toLowerCase().trim();

// Earliest stop month per lineage: stopping any member stops the whole chain.
function lineageStops(transactions: Transaction[]): Map<string, string> {
  const stops = new Map<string, string>();
  for (const tx of transactions) {
    if (!tx.stoppedAfterMonth) continue;
    const prev = stops.get(rootOf(tx));
    if (!prev || tx.stoppedAfterMonth < prev) stops.set(rootOf(tx), tx.stoppedAfterMonth);
  }
  return stops;
}

const isStopped = (tx: Transaction, ym: string, stops: Map<string, string>) => {
  const stop = stops.get(rootOf(tx));
  return !!stop && ym >= stop;
};

const ownMonth = (transactions: Transaction[], ym: string, stops: Map<string, string>) =>
  transactions.filter((tx) => toYearMonth(tx.transactionTime) === ym && !isStopped(tx, ym, stops));

// Projects each Fixed Monthly lineage into `ym`. The latest member dated before `ym` is the template,
// so an amount/date/time edit made in a later month is what gets copied into every month after it.
function carryOver(transactions: Transaction[], ym: string, own: Transaction[], stops: Map<string, string>): Transaction[] {
  const templates = new Map<string, Transaction>();
  for (const tx of transactions) {
    if (!isRecurringFixed(tx) || toYearMonth(tx.transactionTime) >= ym) continue;
    const cur = templates.get(rootOf(tx));
    if (!cur || new Date(tx.transactionTime) > new Date(cur.transactionTime)) templates.set(rootOf(tx), tx);
  }

  const [y, m] = ym.split('-').map(Number);
  const daysInMonth = new Date(y, m, 0).getDate();
  const placed = [...own];
  const carried: Transaction[] = [];

  for (const [root, tpl] of templates) {
    if (isStopped(tpl, ym, stops)) continue;
    // Slot already occupied by a real entry of this lineage (or a same-titled manual entry)
    if (placed.some((e) => e.id === root || e.parentFixedId === root || titleKey(e) === titleKey(tpl))) continue;

    const src = new Date(tpl.transactionTime);
    const projected: Transaction = {
      ...tpl,
      id: `fixed-${tpl.id}-${ym}`,
      parentFixedId: root,
      transactionTime: new Date(y, m - 1, Math.min(src.getDate(), daysInMonth), src.getHours(), src.getMinutes()).toISOString(),
      isAutoGenerated: true,
    };
    placed.push(projected);
    carried.push(projected);
  }
  return carried;
}

/** Real entries of `ym` plus Fixed Monthly carry-overs from earlier months. */
export function scopeMonth(transactions: Transaction[], ym: string): Transaction[] {
  const stops = lineageStops(transactions);
  const own = ownMonth(transactions, ym, stops);
  return [...own, ...carryOver(transactions, ym, own, stops)];
}

/** Every real entry plus carry-overs for each month from the first entry through `untilYM`. */
export function scopeAll(transactions: Transaction[], untilYM: string): Transaction[] {
  const stops = lineageStops(transactions);
  const result = transactions.filter((tx) => !isStopped(tx, toYearMonth(tx.transactionTime), stops));
  if (transactions.length === 0) return result;

  // ponytail: carry-overs stop at untilYM (current month); future months would be unbounded
  const first = transactions.map((tx) => toYearMonth(tx.transactionTime)).sort()[0];
  for (let ym = first; ym <= untilYM; ) {
    result.push(...carryOver(transactions, ym, ownMonth(transactions, ym, stops), stops));
    const [y, m] = ym.split('-').map(Number);
    ym = ymOfDate(new Date(y, m, 1));
  }
  return result;
}
