import React, { useState } from 'react';
import type { TargetCurrency, Transaction, ValuatedTransaction } from './types';
import { useTransactions } from './hooks/useTransactions';
import { useExchangeRates } from './hooks/useExchangeRates';
import { useValuationEngine } from './hooks/useValuationEngine';
import { useBudgets } from './hooks/useBudgets';

import { Header } from './components/Header';
import { ControlBar } from './components/ControlBar';
import { FloatingAddButton } from './components/FloatingAddButton';
import { MetricCards } from './components/MetricCards';
import { CalendarMatrixView } from './components/CalendarMatrixView';
import { FilteredListView } from './components/FilteredListView';
import { BreakdownAnalyticsView } from './components/BreakdownAnalyticsView';
import { BudgetPlanningView } from './components/BudgetPlanningView';
import { ExpenseModal } from './components/ExpenseModal';
import { STATIC_FALLBACK_RATES } from './repositories/LocalStorageExchangeRateRepository';
import { toLocalDateString } from './utils/currency';

export const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'dashboard' | 'calendar' | 'transactions' | 'analytics' | 'budget'>('dashboard');
  const [targetCurrency, setTargetCurrency] = useState<TargetCurrency>('KRW');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);

  // Global Month Filter: YYYY-MM (e.g. "2026-09") or "ALL"
  const now = new Date();
  const defaultYM = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const [selectedYearMonth, setSelectedYearMonth] = useState<string>(defaultYM);

  // Hook 1: Data storage layer
  const { transactions, addTransactionsBatch, editTransaction, removeTransaction } = useTransactions();

  // Hook 2: Exchange rates sync and prefetching
  const { ratesMap } = useExchangeRates(transactions);

  // Filter transactions by selected month (including persistent fixed expenses carryover)
  const scopedTransactions = React.useMemo(() => {
    if (selectedYearMonth === 'ALL') {
      return transactions;
    }

    // 1. Transactions originally recorded in this month
    const originalThisMonth = transactions.filter((tx) => {
      const txLocalDate = toLocalDateString(tx.transactionTime);
      return txLocalDate.startsWith(selectedYearMonth);
    });

    // 2. Fixed recurring expenses originating from prior months that should carry over
    // (A fixed expense created in month M carries over to all months >= M)
    const fixedCarriedOver: Transaction[] = [];

    // Find all fixed expenses created in earlier months
    for (const tx of transactions) {
      if (tx.isFixed || tx.expenseNature === 'RECURRING_MONTHLY') {
        const txLocalDate = toLocalDateString(tx.transactionTime);
        const originYearMonth = txLocalDate.slice(0, 7);

        // If origin is strictly before selectedYearMonth
        if (originYearMonth < selectedYearMonth) {
          // Check if there is already an explicit transaction for this month with the same description
          const alreadyExists = originalThisMonth.some(
            (existing) => existing.description === tx.description
          );

          if (!alreadyExists) {
            // Project the fixed transaction into the selected month on the same day of month
            const originDay = txLocalDate.slice(8, 10);
            const projectedDate = `${selectedYearMonth}-${originDay}`;
            fixedCarriedOver.push({
              ...tx,
              id: `fixed-${tx.id}-${selectedYearMonth}`,
              transactionTime: `${projectedDate}T12:00:00.000Z`,
              isFixed: true,
              isAutoGenerated: true,
            });
          }
        }
      }
    }

    return [...originalThisMonth, ...fixedCarriedOver].sort(
      (a, b) => new Date(b.transactionTime).getTime() - new Date(a.transactionTime).getTime()
    );
  }, [transactions, selectedYearMonth]);

  // Hook 3: Real-time dynamic valuation engine on scoped transactions
  const { valuatedList, calendarMap, breakdown } = useValuationEngine(scopedTransactions, ratesMap, targetCurrency);

  // Hook 4: Budget planning storage
  const { budgetsMap, updateBudget } = useBudgets();

  const handleOpenAddModal = () => {
    setEditingTx(null);
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (tx: ValuatedTransaction) => {
    setEditingTx(tx);
    setIsModalOpen(true);
  };

  const handleBatchSubmit = async (items: Array<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>) => {
    await addTransactionsBatch(items);
  };

  const handleUpdateSingle = async (
    id: string,
    updates: Partial<Omit<Transaction, 'id' | 'createdAt' | 'updatedAt'>>
  ) => {
    await editTransaction(id, updates);
  };

  // Compute selected month's budget in targetCurrency
  const activeYM = selectedYearMonth === 'ALL' ? defaultYM : selectedYearMonth;
  const currentBudgetRecord = budgetsMap[activeYM];
  const rateRecord = ratesMap[`${activeYM}-01`] || ratesMap[Object.keys(ratesMap)[0]] || STATIC_FALLBACK_RATES;
  const rates = rateRecord.rates;

  let currentMonthlyBudgetInTarget: number | undefined = undefined;
  let currentFixedBudgetInTarget: number | undefined = undefined;
  let currentFreeBudgetInTarget: number | undefined = undefined;

  if (currentBudgetRecord) {
    const budgetInKrw =
      currentBudgetRecord.currency === 'KRW'
        ? currentBudgetRecord.totalBudget
        : currentBudgetRecord.totalBudget * (rates[currentBudgetRecord.currency] || STATIC_FALLBACK_RATES.rates[currentBudgetRecord.currency]);
    
    currentMonthlyBudgetInTarget =
      targetCurrency === 'KRW'
        ? Math.round(budgetInKrw)
        : Number((budgetInKrw / (rates[targetCurrency] || STATIC_FALLBACK_RATES.rates[targetCurrency] || 1)).toFixed(2));

    const fixedInKrw =
      currentBudgetRecord.fixedBudget !== undefined
        ? currentBudgetRecord.currency === 'KRW'
          ? currentBudgetRecord.fixedBudget
          : currentBudgetRecord.fixedBudget * (rates[currentBudgetRecord.currency] || STATIC_FALLBACK_RATES.rates[currentBudgetRecord.currency])
        : budgetInKrw * 0.45;

    currentFixedBudgetInTarget =
      targetCurrency === 'KRW'
        ? Math.round(fixedInKrw)
        : Number((fixedInKrw / (rates[targetCurrency] || STATIC_FALLBACK_RATES.rates[targetCurrency] || 1)).toFixed(2));

    const freeInKrw =
      currentBudgetRecord.freeBudget !== undefined
        ? currentBudgetRecord.currency === 'KRW'
          ? currentBudgetRecord.freeBudget
          : currentBudgetRecord.freeBudget * (rates[currentBudgetRecord.currency] || STATIC_FALLBACK_RATES.rates[currentBudgetRecord.currency])
        : budgetInKrw * 0.55;

    currentFreeBudgetInTarget =
      targetCurrency === 'KRW'
        ? Math.round(freeInKrw)
        : Number((freeInKrw / (rates[targetCurrency] || STATIC_FALLBACK_RATES.rates[targetCurrency] || 1)).toFixed(2));
  }

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Sticky App Header: Clean & Minimal */}
      <Header
        activeTab={activeTab}
        setActiveTab={setActiveTab}
      />

      {/* Main Container */}
      <main style={{ flex: 1, paddingTop: '1.25rem', paddingBottom: '3rem' }}>
        <div className="container">
          {/* Top Control Bar: Month Navigator (Prev/Next/This Month/All) & Currency Selector */}
          <ControlBar
            selectedYearMonth={selectedYearMonth}
            setSelectedYearMonth={setSelectedYearMonth}
            targetCurrency={targetCurrency}
            setTargetCurrency={setTargetCurrency}
          />

          {/* Always Display Key Metric KPI Overview with Fixed/Free budget analysis */}
          <MetricCards
            breakdown={breakdown}
            targetCurrency={targetCurrency}
            totalTransactionsCount={scopedTransactions.length}
            monthlyBudget={currentMonthlyBudgetInTarget}
            fixedBudget={currentFixedBudgetInTarget}
            freeBudget={currentFreeBudgetInTarget}
            onGoToBudget={() => setActiveTab('budget')}
          />

          {/* Tab Views */}
          {activeTab === 'dashboard' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
              {/* Top View: Breakdown Analytics */}
              <BreakdownAnalyticsView breakdown={breakdown} targetCurrency={targetCurrency} />

              {/* Bottom View: Recent Transactions List */}
              <FilteredListView
                transactions={valuatedList}
                targetCurrency={targetCurrency}
                onEdit={handleOpenEditModal}
                onDelete={removeTransaction}
              />
            </div>
          )}

          {activeTab === 'calendar' && (
            <CalendarMatrixView
              calendarMap={calendarMap}
              targetCurrency={targetCurrency}
              onSelectTransaction={handleOpenEditModal}
              selectedYearMonth={selectedYearMonth}
              onMonthChange={setSelectedYearMonth}
            />
          )}

          {activeTab === 'transactions' && (
            <FilteredListView
              transactions={valuatedList}
              targetCurrency={targetCurrency}
              onEdit={handleOpenEditModal}
              onDelete={removeTransaction}
            />
          )}

          {activeTab === 'analytics' && (
            <BreakdownAnalyticsView breakdown={breakdown} targetCurrency={targetCurrency} />
          )}

          {activeTab === 'budget' && (
            <BudgetPlanningView
              budgetsMap={budgetsMap}
              onSaveBudget={updateBudget}
              ratesMap={ratesMap}
              targetCurrency={targetCurrency}
              breakdown={breakdown}
              selectedYearMonth={selectedYearMonth}
              onMonthChange={setSelectedYearMonth}
            />
          )}
        </div>
      </main>

      {/* Footer */}
      <footer
        style={{
          borderTop: '1px solid var(--border-light)',
          backgroundColor: 'var(--bg-primary)',
          padding: '1.25rem 0',
          textAlign: 'center',
          fontSize: '0.8125rem',
          color: 'var(--text-muted)',
        }}
      >
        <div className="container">
          Tallyon Multi-Currency Expense Tracker • Built with React 19, TypeScript & Repository Architecture
        </div>
      </footer>

      {/* Floating Pencil Add Expense Button (Bottom-Right) */}
      <FloatingAddButton onClick={handleOpenAddModal} />

      {/* Expense Add / Edit Modal */}
      <ExpenseModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSubmitBatch={handleBatchSubmit}
        editingTransaction={editingTx}
        onUpdateSingle={handleUpdateSingle}
      />
    </div>
  );
};

export default App;
